<?php

namespace SfRestApi\Request;

use SfRestApi\Contracts\RequestInterface;

/**
 * Class BatchRequest
 *
 * @package SfRestApi\Request
 */
class BatchRequest extends BaseRequest implements RequestInterface
{
    public static $_instance;

    public static function getInstance() {
        if( !isset( self::$_instance )) {
            self::$_instance = new self();
        }

        return self::$_instance;
    }

    public function query() {}

    public function getConfig()
    {
        return parent::getConfig(); // TODO: Change the autogenerated stub
    }

    public function insert ()
    {
        // TODO: Implement insert() method.
    }
    public function update ()
    {
        // TODO: Implement update() method.
    }
    public function delete ()
    {
        // TODO: Implement delete() method.
    }

    /**
     * Insert Method
     *
     * @param array $args
     *
     * @return string

    public function insert(array $args): string
    {
        $args['records'] = $this->prepBatch('POST', $args['records']);
        $uri = $this->getConfig()->getBaseUri().'/composite/tree/'.$args['object'];
        foreach( $args['records'] as $r ) {
            $result[] = $this->send('POST',$uri,$r);
        }
        return json_encode( $result );
    } */

    /**
     * Update Method
     *
     * @param array $args
     *
     * @return string

    public function update(array $args): string
    {
        if( count(json_decode($args['records'])) > 1) {

        }
        $results = $this->request->send('PATCH'
            ,$this->request->getConfig()->getBaseUri().'/sobjects/'.$args['object'].'/'.$args['id']
            ,$args['records']);

        return $results;
    } */

    /**
     * Delete Method
     *
     * @param array $args
     *
     * @return string

    public function delete(array $args): string
    {
        $results = $this->request->send('DELETE'
            ,$this->request->getConfig()->getBaseUri().'/sobjects/'.$args['object'].'/'.$args['id']
            ,'');

        return $results;
    }*/
}