<?php

namespace SfRestApi\Request;

use SfRestApi\Contracts\ClientConfigInterface;
use SfRestApi\Contracts\RequestInterface;

/**
 * Class Request
 *
 * @todo DELETE
 *
 * @package SfRestApi\Config
 * @author Nathan Alessandro <nalessan@gmail.com>
 */
class Request extends BaseRequest implements RequestInterface
{
    public static $_instance;

    public static function getInstance() {
        if( !isset( self::$_instance )) {
            self::$_instance = new self();
        }

        return self::$_instance;
    }

    public function getConfig()
    {
        return parent::getConfig(); // TODO: Change the autogenerated stub
    }

    public function query() {}

    public function insert ()
    {
        // TODO: Implement insert() method.
    }
    public function update ()
    {
        // TODO: Implement update() method.
    }
    public function delete ()
    {
        // TODO: Implement delete() method.
    }


}